server:
  ssl:
    enabled: true
    key-alias: test
    key-store: classpath:test.keystore
    key-store-password: testtest
    key-password: testtest


spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/afarensis?currentSchema=afarensis&serverTimezone=Asia/Seoul
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 27
      minimum-idle: 54
      pool-name: afarensis-pool
      connection-test-query: SELECT 1
      connection-timeout: 3000
      validation-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 18000
      schema: afarensis
      health-check-properties:
        maximumTimeout: 3000
        validationQuery: SELECT 1
        validationQueryTimeout: 3000



  devtools:
    livereload:
      enabled: true

  flyway:
    out-of-order: true
    schemas: afarensis
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres
    validate-on-migrate: true
    validate-migration-naming: true

jwt:
  secret: c2R2c2RsdmlqZHM7dmlqYTsnb3NkaWpmYW85d2V1cndhZWxrbnZtbC54Y252bGl6dXhjaHZwOHN2OGloamFzO2RsdmtuY

#file:
#  storage:
#    dir: /Users/yuseungcheol/Desktop/test

logging:
  level:
    com.: debug
    org.hibernate: debug
    org.springframework.web: debug
    org.springframework.http: debug
    org.flywaydb.: debug
  file:
    path: ./logs

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, refresh
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: "server"
