server:
  ssl:
    enabled: true
    key-alias: test
    key-store: classpath:test.keystore
    key-store-password: testtest
    key-password: testtest

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/afarensis?currentSchema=afarensis&serverTimezone=Asia/Seoul
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 21

  devtools:
    livereload:
      enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres
    validate-on-migrate: true
    validate-migration-naming: true

jwt:
  secret: c2R2c2RsdmlqZHM7dmlqYTsnb3NkaWpmYW85d2V1cndhZWxrbnZtbC54Y252bGl6dXhjaHZwOHN2OGloamFzO2RsdmtuY

#file:
#  storage:
#    dir: /Users/yuseungcheol/Desktop/test

#logging:
#  level:
#    com.: trace
#  file:
#    path: ./logs

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, refresh
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: "server"
